/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 20 21:07:50 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CLASS_023fa3df801cfbc2fb6ebd26ba50452b1da83b840005047bd6edcc7edde134e0_ESTest extends CLASS_023fa3df801cfbc2fb6ebd26ba50452b1da83b840005047bd6edcc7edde134e0_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Boolean boolean0 = Boolean.TRUE;
      boolean boolean1 = CLASS_023fa3df801cfbc2fb6ebd26ba50452b1da83b840005047bd6edcc7edde134e0.converseBoolean(boolean0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = CLASS_023fa3df801cfbc2fb6ebd26ba50452b1da83b840005047bd6edcc7edde134e0.converseBoolean((Boolean) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CLASS_023fa3df801cfbc2fb6ebd26ba50452b1da83b840005047bd6edcc7edde134e0 cLASS_023fa3df801cfbc2fb6ebd26ba50452b1da83b840005047bd6edcc7edde134e0_0 = new CLASS_023fa3df801cfbc2fb6ebd26ba50452b1da83b840005047bd6edcc7edde134e0();
  }
}
