/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 19 08:26:21 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CLASS_02354123ff83fb6cc72cb5540c1812a533e5b2bfa9c5674d7d0e059ef050041f_ESTest extends CLASS_02354123ff83fb6cc72cb5540c1812a533e5b2bfa9c5674d7d0e059ef050041f_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CLASS_02354123ff83fb6cc72cb5540c1812a533e5b2bfa9c5674d7d0e059ef050041f cLASS_02354123ff83fb6cc72cb5540c1812a533e5b2bfa9c5674d7d0e059ef050041f0 = new CLASS_02354123ff83fb6cc72cb5540c1812a533e5b2bfa9c5674d7d0e059ef050041f();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = CLASS_02354123ff83fb6cc72cb5540c1812a533e5b2bfa9c5674d7d0e059ef050041f.copyValueOf((char[]) null);
      assertNull(string0);
  }
}
