/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 20 06:33:01 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CLASS_002b132ad75cae1a61c2c718b925efbed3ae784f9c2d72005aa0ea8e59c326fc_ESTest extends CLASS_002b132ad75cae1a61c2c718b925efbed3ae784f9c2d72005aa0ea8e59c326fc_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double double0 = CLASS_002b132ad75cae1a61c2c718b925efbed3ae784f9c2d72005aa0ea8e59c326fc.testSubConstD(32.0);
      assertEquals(0.0, double0, 1.0E-4);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      double double0 = CLASS_002b132ad75cae1a61c2c718b925efbed3ae784f9c2d72005aa0ea8e59c326fc.testSubConstD((double)20873.386);
      assertEquals((-20841.386), double0, 1.0E-4);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CLASS_002b132ad75cae1a61c2c718b925efbed3ae784f9c2d72005aa0ea8e59c326fc cLASS_002b132ad75cae1a61c2c718b925efbed3ae784f9c2d72005aa0ea8e59c326fc0 = new CLASS_002b132ad75cae1a61c2c718b925efbed3ae784f9c2d72005aa0ea8e59c326fc();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      double double0 = CLASS_002b132ad75cae1a61c2c718b925efbed3ae784f9c2d72005aa0ea8e59c326fc.testSubConstD((double)0.0F);
      assertEquals(32.0, double0, 1.0E-4);
  }
}
