/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 21 03:23:19 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CLASS_0156e303db12f3fac41e7ec99f745b2957dc21939ab83f5a0c751a66106780ed_ESTest extends CLASS_0156e303db12f3fac41e7ec99f745b2957dc21939ab83f5a0c751a66106780ed_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long long0 = CLASS_0156e303db12f3fac41e7ec99f745b2957dc21939ab83f5a0c751a66106780ed.negMulLong(1L, (-74133L));
      assertEquals(148266L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      long long0 = CLASS_0156e303db12f3fac41e7ec99f745b2957dc21939ab83f5a0c751a66106780ed.negMulLong(760L, 760L);
      assertEquals((-578360L), long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      long long0 = CLASS_0156e303db12f3fac41e7ec99f745b2957dc21939ab83f5a0c751a66106780ed.negMulLong((-1L), (-1L));
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CLASS_0156e303db12f3fac41e7ec99f745b2957dc21939ab83f5a0c751a66106780ed cLASS_0156e303db12f3fac41e7ec99f745b2957dc21939ab83f5a0c751a66106780ed0 = new CLASS_0156e303db12f3fac41e7ec99f745b2957dc21939ab83f5a0c751a66106780ed();
  }
}
