/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 20 10:57:51 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CLASS_e045b894a398fa5a7c3d01989ac428e64d97f7e5ca0b12bf56e8a32ffa9b8396_ESTest extends CLASS_e045b894a398fa5a7c3d01989ac428e64d97f7e5ca0b12bf56e8a32ffa9b8396_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long[] longArray0 = new long[0];
      long long0 = CLASS_e045b894a398fa5a7c3d01989ac428e64d97f7e5ca0b12bf56e8a32ffa9b8396.sum(longArray0, 0, 0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      long[] longArray0 = new long[4];
      long long0 = CLASS_e045b894a398fa5a7c3d01989ac428e64d97f7e5ca0b12bf56e8a32ffa9b8396.sum(longArray0, 17676, 0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      long[] longArray0 = new long[6];
      longArray0[0] = 60602L;
      long long0 = CLASS_e045b894a398fa5a7c3d01989ac428e64d97f7e5ca0b12bf56e8a32ffa9b8396.sum(longArray0, 0, 3);
      assertEquals(60602L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      long[] longArray0 = new long[4];
      longArray0[0] = (-6892L);
      long long0 = CLASS_e045b894a398fa5a7c3d01989ac428e64d97f7e5ca0b12bf56e8a32ffa9b8396.sum(longArray0, 0, 1);
      assertEquals((-6892L), long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CLASS_e045b894a398fa5a7c3d01989ac428e64d97f7e5ca0b12bf56e8a32ffa9b8396 cLASS_e045b894a398fa5a7c3d01989ac428e64d97f7e5ca0b12bf56e8a32ffa9b8396_0 = new CLASS_e045b894a398fa5a7c3d01989ac428e64d97f7e5ca0b12bf56e8a32ffa9b8396();
  }
}
